name: Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - SERG
        - ALEX
      environment:
        type: environment
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      
   #   - name: Set up Docker Buildx
   #     uses: docker/setup-buildx-action@v1
      
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v1  
      
      - name: Run a one-line script
        run: |
          echo Hello, world "${{ github.event.inputs.name }}"!
          ls -la
          echo "${{ github.event.inputs.environment }}"
          echo "This is ${{ vars.TESTENV }}"

      - name: Run connect with ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600  ~/.ssh/id_rsa
          echo 51.250.26.119 > ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no sluser@51.250.26.119 ls -la
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          
      - name: Install and configure docker
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
          docker-compose -H ssh://sluser@51.250.26.119 ls
        shell: bash

      
